# Generated by Django 6.0.3 on 2026-04-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
